### ISSUE TITLE
Multiple matches?

### ISSUE THREAD

**Issue by rhiaro** [Open-Telecoms-Data/ofds_consolidation_tool#15]
What if one node/span from network A matches several nodes/spans from network B? At the moment this is ‘first come first served’

**Comment by rhiaro** [comment]
https://github.com/Open-Telecoms-Data/ofds_consolidation_tool/pull/30 prevents the user from making multiple matches on the same node

**Comment by R2ZER0** [comment]
At the moment, we have the assumption that individual input networks are already de-duplicated - but if the user tried to dedup 3 (or more) nodes, then 2 (or more) of those nodes would have to come from the same network - which implies that the input network wasn't already de-duplicated.

So I think In order to support multi-matching, we'd have to do away with the assumption that input networks are already de-duplicated. Then that means, we could also theoretically run the tool with just one network, de-duplicating within itsself.
